version: "2"

services:
  # application
  website:
    build:
      context: .
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql-blog:db
    environment:
      - DB_HOST=db
      - API_HOST=http://api:8000
      - API_KEY=key123
      - API_SECRET=sec123

  # other service
  api:
    image: quay.io/marc_meszaros/api:v0.0.14
    command: api migrate
    depends_on:
      - mysql-api
      - redis
    ports:
      - "8000:80"
    environment:
      - DJANGO_DEBUG=true
      - CLOUDFILES_IMAGES_PREFIX=marc_images_
      - SNAP_AUTHENTICATION=false
      - SNAP_AUTHORIZATION=false
      - DATABASE_HOST=mysql-api
      - DATABASE_PORT=3307
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  # third-party
  redis:
    image: redis:3.0-alpine

  mysql-api:
    image: mysql:5.5
    ports:
      - "3307:3306" # to connect with an SQL client
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpass
      - MYSQL_USER=snapableusr
      - MYSQL_PASSWORD=snapable12345
      - MYSQL_DATABASE=snapabledb

  mysql-blog:
    image: mysql:5.5
    ports:
      - "3306:3306" # to connect with an SQL client
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpass
      - MYSQL_USER=blog_usr
      - MYSQL_PASSWORD=vj5pVr8Lg0B6C8Hb
      - MYSQL_DATABASE=blog
